### ISSUE TITLE
关于检测字体框的问题

### ISSUE THREAD

**Issue by solamn-1042** [bubbliiiing/ssd-pytorch#105]
由于Pillow库版本问题：
将源代码ssd.py中的label_size = draw.textsize(label, font)更改为了label_size = draw.textlength(label, font)，
但此时会报错：
Traceback (most recent call last):
  File "d:\Study\CodeSoft\MyProject\ssd-pytorch-master\predict.py", line 87, in <module>
    r_image = ssd.detect_image(image, crop=crop, count=count)
  File "d:\Study\CodeSoft\MyProject\ssd-pytorch-master\ssd.py", line 227, in detect_image
    if top - label_size[1] >= 0:
TypeError: 'float' object is not subscriptable

此时修改源码：
if top - label_size[1] >= 0:
                text_origin = np.array([left, top - label_size[1]])
            else:
                text_origin = np.array([left, top + 1])
为：
if top - label_size >= 0:
                text_origin = np.array([left, top - label_size])
            else:
                text_origin = np.array([left, top])
即可消除报错，但是此时预测的类别字体框会非常的长，想请问一下可以从哪里进行修改？
附：[预测后图片链接](https://i.postimg.cc/J004dhgt/1-predict.jpg)

**Comment by solamn-1042** [comment]
bbox = draw.textbbox((0, 0), label, font)
label_width = bbox[2] - bbox[0]
label_height = bbox[3] - bbox[1]
label = label.encode('utf-8')
print(label, top, left, bottom, right)
            
if top - label_height >= 0:
    text_origin = np.array([left, top - label_height])
else:
    text_origin = np.array([left, top])
