### ISSUE TITLE
训练自己数据集时，train.py报错？向大佬求助

### ISSUE THREAD

**Issue by Cai-ops** [bubbliiiing/ssd-pytorch#11]
Loading weights into state dict...
Finished!
Traceback (most recent call last):
  File "/data/iiot-data/caixh/ssd-pytorch/train.py", line 108, in <module>
    out = net(images)
  File "/home/amax/anaconda3/envs/iiot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/anaconda3/envs/iiot/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/amax/anaconda3/envs/iiot/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/amax/anaconda3/envs/iiot/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/amax/anaconda3/envs/iiot/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/amax/anaconda3/envs/iiot/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/amax/anaconda3/envs/iiot/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    assert all(map(lambda i: i.is_cuda, inputs))
AssertionError
不知道bug如何解决？

**Comment by bubbliiiing** [comment]
版本？驱动？

**Comment by Cai-ops** [comment]
我重新指定GPU设备解决啦，具体原因还未深究。

**Comment by Momaek-w** [comment]
> 我重新指定GPU设备解决啦，具体原因还未深究。

我也遇到相同的情况请问如何解决的呢

**Comment by bubbliiiing** [comment]
unknown，我是贫穷仔，没有多卡

**Comment by animation123** [comment]
> 我重新指定GPU设备解决啦，具体原因还未深究。

执行楼主的train.py代码时，也碰到了这个问题，请问层主是怎么解决的？
Loading weights into state dict...
Finished!
Epoch 1/50:   0%|          | 0/59 [00:00<?, ?it/s<class 'dict'>]Start Train
Epoch 1/50:   0%|          | 0/59 [00:05<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "/home/wzz/Desktop/Qi/ssd-pytorch-master/train.py", line 205, in <module>
    fit_one_epoch(net,criterion,epoch,epoch_size,epoch_size_val,gen,gen_val,Freeze_Epoch,Cuda)
  File "/home/wzz/Desktop/Qi/ssd-pytorch-master/train.py", line 56, in fit_one_epoch
    out = net(images)
  File "/home/wzz/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wzz/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/wzz/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/wzz/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/wzz/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/wzz/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/wzz/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    assert all(map(lambda i: i.is_cuda, inputs))
AssertionError

**Comment by bubbliiiing** [comment]
指定GPU设备兄弟
