### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by yypsWinnie** [bubbliiiing/ssd-pytorch#3]
Traceback (most recent call last):
  File "E:/python/Semantic_Segmentation/ssd/voc_annotation.py", line 30, in <module>
    convert_annotation(year, image_id, list_file)
  File "E:/python/Semantic_Segmentation/ssd/voc_annotation.py", line 20, in convert_annotation
    b = (int(xmlbox.find('xmin').text), int(xmlbox.find('ymin').text), int(xmlbox.find('xmax').text), int(xmlbox.find('ymax').text))
ValueError: invalid literal for int() with base 10: '45.70000076293945'

使用VOC2012数据集时报错，不知道引起问题的原因是？

**Comment by bubbliiiing** [comment]
因为那个对应的xml数字太长，改短了就行
