### ISSUE TITLE
使用自己的模型显示_pickle.UnpicklingError: invalid load key, '\x0a'.

### ISSUE THREAD

**Issue by lychee749** [bubbliiiing/ssd-pytorch#71]
我的模型是pb格式，放入model_path然后报错_pickle.UnpicklingError: invalid load key, '\x0a'.

Traceback (most recent call last):
  File "d:\Users\ssd-pytorch-master\predict.py", line 14, in <module>
    ssd = SSD()
  File "d:\Users\ssd-pytorch-master\ssd.py", line 102, in __init__
    self.generate()
  File "d:\Users\ssd-pytorch-master\ssd.py", line 123, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "D:\Python36\lib\site-packages\torch\serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\Python36\lib\site-packages\torch\serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.

**Comment by bubbliiiing** [comment]
为什么你的模型是pb格式
