### ISSUE TITLE
ValueError: Number of samples, -1, must be non-negative.

### ISSUE THREAD

**Issue by WestHan33** [bubbliiiing/ssd-pytorch#76]
大佬您好，有一个问题想请教您，我在训练您的SSD代码的时候，出现了如下问题，请问您知道是什么原因吗？
Traceback (most recent call last):
  File "D:\ssd-pytorch-master\train.py", line 266, in <module>
    anchors = get_anchors(input_shape, anchors_size, backbone)
  File "D:\ssd-pytorch-master\utils\anchors.py", line 136, in get_anchors
    anchor_boxes = AnchorBox(input_shape, anchors_size[i], max_size = anchors_size[i+1], 
  File "D:\ssd-pytorch-master\utils\anchors.py", line 66, in call
    linx = np.linspace(0.5 * step_x, img_width - 0.5 * step_x,
  File "<__array_function__ internals>", line 180, in linspace
  File "D:\anaconda3\envs\yolov5\lib\site-packages\numpy\core\function_base.py", line 122, in linspace
    raise ValueError("Number of samples, %s, must be non-negative." % num)
ValueError: Number of samples, -1, must be non-negative.
 
同样的环境我用您的yolov4-tiny的代码训练就没有问题。谢谢您

**Comment by WestHan33** [comment]
不好意思博主，找到原因了，权重文件加载错了。问题已经解决。
