### ISSUE TITLE
大佬，predict预测时终端显示了预测结果但是不显示图片了，是为什么呢

### ISSUE THREAD

**Issue by dangaoxia9** [bubbliiiing/ssd-pytorch#98]

**Comment by bubbliiiing** [comment]
额 服务器把？

**Comment by dangaoxia9** [comment]
> 额 服务器把？

对的，是服务器跑的

**Comment by bubbliiiing** [comment]
没有可视化界面

**Comment by dangaoxia9** [comment]
> 没有可视化界面

Input image filename:img/20200525141658.png
img/20200525141658.png
Traceback (most recent call last):
  File "/root/ssd-pytorch-master/predict.py", line 84, in <module>
    r_image = ssd.detect_image(image, crop=crop, count=count)
  File "/root/ssd-pytorch-master/ssd.py", line 162, in detect_image
    results     = self.bbox_util.dec
AttributeError: 'BBoxUtility' object has no attribute 'dec'

Process finished with exit code 1

大佬，我运行predict时出现了这个错误，这是怎么了

**Comment by bubbliiiing** [comment]
欸？这个是你改了吗？为什么只剩dec？

**Comment by dangaoxia9** [comment]
> 欸？这个是你改了吗？为什么只剩dec？

没有改的

**Comment by dangaoxia9** [comment]
Input image filename:img/1.png
img/1.png
b'0 0.99' 156 161 222 204
b'1 0.96' 157 216 220 259
b'2 0.89' 154 272 215 312
b'5 0.96' 153 378 216 420
b'8 0.97' 156 325 214 364

大佬，只有结果没有可视化界面怎么办呀

**Comment by bubbliiiing** [comment]
因为在服务器吗

**Comment by dangaoxia9** [comment]
> 因为在服务器吗

对，是用的服务器，就不显示图片

**Comment by dingyan-dy** [comment]
> > 因为在服务器吗
> 
> 对，是用的服务器，就不显示图片

您好，你这个问题解决了吗？我现在也是只显示终端结果，但绘制图像显示的还是原图，但是用street.jpg测试的是正常的，不知道问题出在哪里了

**Comment by junfengwang04** [comment]
大佬，你解决了吗，我就是只有终端显示，没有图片出来，没有用服务器PS D:\Python\ssd-pytorch-master> python predict.py
logs/best_epoch_weights.pth model, anchors, and classes loaded.
Configurations:
----------------------------------------------------------------------
|                     keys |                                   values|
----------------------------------------------------------------------
|               model_path |              logs/best_epoch_weights.pth|
|             classes_path |               model_data/voc_classes.txt|
|              input_shape |                               [300, 300]|
|                 backbone |                                      vgg|
|               confidence |                                      0.5|
|                  nms_iou |                                     0.45|
|             anchors_size |        [30, 60, 111, 162, 213, 264, 315]|
|          letterbox_image |                                    False|
|                     cuda |                                    False|
----------------------------------------------------------------------
Input image filename:img/street.jpg
PS D:\Python\ssd-pytorch-master>
